### PR TITLE
Adding Nagios image name/version parameters.

### PR DESCRIPTION
**Pull request by danbev**
Motivation:
Currently the Nagios image name version as specified in the template and
are not configurable without manually editing the template. Adding
template parameters would allow for the name and version to be updated
when the template is used.

Modifications:
Added NAGIOS_IMAGE_NAME and NAGIOS_IMAGE_VERSION parameters.

Result:
The template can be processed and the NAGIOS_IMAGE_NAME and
NAGIOS_IMAGE_VERSION can be specified:

$ oc process -f nagios.yml -v NAGIOS_IMAGE_NAME=rhmap4/nagios -v
NAGIOS_IMAGE_VERSION=4.0.8-6 -v NAGIOS_HOST=www.example.com -v
SMTP_USERNAME=dummy -v SMTP_PASSWORD=dummy

JIRA:
https://issues.jboss.org/browse/RHMAP-5962

### CODE REVIEW

**Comment by danbev** [comment]
@luigizuccarelli I've updated the build number for travis now. Let me know if this looks alright and I'll get it merged.

**Comment by luigizuccarelli** [comment]
@danbev Ok looks good - for the verification I will use  -v NAGIOS_IMAGE_NAME=rhmap/nagios -v
NAGIOS_IMAGE_VERSION=4.0.8-3

**Comment by luigizuccarelli** [comment]
@danbev Verified on osm2 - refer to JIRA RHMAP-5962

**Comment by danbev** [comment]
@luigizuccarelli Thanks for the review!

**Pull request merged**
